flaskstarter/settings/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms.fields.html5 import EmailField
from wtforms import ValidationError, TextField, PasswordField, SubmitField
from wtforms.validators import (Required, Length, EqualTo, Email)
from flask_login import current_user

from ..user import Users
from ..utils import PASSWORD_LEN_MIN, PASSWORD_LEN_MAX


class ProfileForm(FlaskForm):
    multipart = True
    name = TextField(u'Name', [Length(max=50)])
    email = EmailField(u'Email', [Required(), Email()])
    submit = SubmitField(u'Update')


class PasswordForm(FlaskForm):
    password = PasswordField('Current password', [Required()])
    new_password = PasswordField('New password', [Required(), Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)])
    password_again = PasswordField('Password again', [Required(), Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX), EqualTo('new_password')])
    submit = SubmitField(u'Update')

    def validate_password(form, field):
        user = Users.get_by_id(current_user.id)
        if not user.check_password(field.data):
            raise ValidationError("Password is wrong")

flaskstarter/tasks/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, SelectField
from wtforms.validators import Required, Length

class MyTaskForm(FlaskForm):
    task = TextAreaField(u'Your Task', [Required(), Length(5, 2048)])
    submit = SubmitField(u'Save Task')

class UmapForm(FlaskForm):
    def __init__(self,choices=[('def','Default')]):
        self.cell_color = SelectField('cell_color',choices=choices)

flaskstarter/__init__.py
# -*- coding: utf-8 -*-

from .app import create_app

flaskstarter/app.py
# -*- coding: utf-8 -*-

from flask import Flask

from .config import DefaultConfig
from .user import Users, UsersAdmin
from .settings import settings
from .tasks import tasks
from .naso_tableview import naso
from .frontend import frontend, ContactUsAdmin
from .extensions import db, mail, cache, login_manager, admin, mongo
from .utils import pretty_date
import logging
import os
from datetime import timedelta

from pymongo import MongoClient
from .model.umap import UmapView
from .model.meta import MetaView

# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
    settings,
    tasks,
    naso
)

logging.basicConfig(level=logging.DEBUG,
                   format='[%(asctime)s]: {} %(levelname)s %(message)s'.format(os.getpid()),
                   datefmt='%Y-%m-%d %H:%M:%S',
                   handlers=[logging.StreamHandler()])

logger = logging.getLogger()


def create_app(config=None, app_name=None, blueprints=None):
    # Create a Flask app

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name,
                instance_relative_config=True)

    # Add 0627 by junyi
    # app.config['LOGIN_DISABLED'] = True
    app.config['SECRET_KEY'] = os.urandom(24)
    app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=30)

    # add db


    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app


def configure_app(app, config=None):
    # Different ways of configurations i.e local or production
    logger.info(f"Starting app in %s environment" % os.getenv('FLASK_ENV'))
    flask_env = os.environ.get('FLASK_ENV')
    if 'development' in flask_env:
        print('configuring for development')
        app.config.from_object(DefaultConfig)
    # if exists under root ./instance/X.cfg
    # app.config.from_pyfile('secret_config.cfg')
    # print(app.instance_path)
    if config:
        app.config.from_object(config)


def configure_extensions(app):

    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # flask-cache
    cache.init_app(app)

    # flask-admin
    # sqlite db data
    admin.add_view(ContactUsAdmin(db.session))
    admin.add_view(UsersAdmin(db.session))

    # mongo db data
    admin.add_view(UmapView(mongo['umap']))
    admin.add_view(MetaView(mongo['single_cell_meta_country']))

    admin.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return Users.query.get(id)
    login_manager.setup_app(app)


def configure_blueprints(app, blueprints):
    # Configure blueprints in views

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    # Configure logging

    if app.debug:
        # Skip debug and test mode. Better check terminal output.
        return

    # TODO: production loggers for (info, email, etc)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return "Oops! You don't have permission to access this page.", 403

    @app.errorhandler(404)
    def page_not_found(error):
        return "Opps! Page not found.", 404

    @app.errorhandler(500)
    def server_error_page(error):
        return "Oops! Internal server error. Please try after sometime.", 500

flaskstarter/frontend/__init__.py
# -*- coding: utf-8 -*-

from .models import ContactUs, ContactUsAdmin

from .views import frontend

flaskstarter/naso_tableview/__init__.py
# -*- coding: utf-8 -*-

from .views import naso

flaskstarter/naso_tableview/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, flash, redirect, url_for, send_file, request, jsonify
from flask_login import login_required, current_user
from ..extensions import db, mongo

from flaskstarter.tasks.forms import UmapForm

import csv
import gzip
import zipfile
import re

import pandas as pd
import numpy as np
import plotly
import plotly.express as px
import json
from ..utils import TMP_FOLDER
import os
import shortuuid
import subprocess
import pandas as pd
import time
from datetime import datetime
from os.path import exists
naso = Blueprint('naso', __name__, url_prefix='/naso')

# sub folders to manage different flask instances: not a good place to put, should be in API endpoint?
user_timestamp = datetime.now().strftime('%Y%m%d%H%M%S%f')
#user_timestamp = "test"
user_tmp = [TMP_FOLDER + "/" + user_timestamp]
print(user_tmp)
os.makedirs(user_tmp[-1])

scClassify_input = []




@naso.route('/show_plot', methods=['GET', 'POST'])
def show_plot():     
    cell_color = request.form.get('name_opt_col')
    if(cell_color is None):
        cell_color = "scClassify_prediction"

    graphJSON, df_plot = plot_umap(cell_color)
    colors = df_plot.columns.values
    return render_template('tasks/show_plot.html', graphJSON=graphJSON, colors=colors)


## Create by junyi
def plot_umap(cell_color='scClassify_prediction'):
    df = pd.read_csv(user_tmp[-1] + '/umap.csv', index_col=0)
    df.columns = ["umap_0", "umap_1"]
    df_meta = pd.read_csv(user_tmp[-1] + '/meta.tsv', index_col=1,sep="\t")
    df_plot = df.merge(df_meta, left_index=True, right_index=True)

    fig = px.scatter(
        df_plot, x="umap_0", y="umap_1",color=cell_color)
    fig.update_layout(
        autosize=False, width=900, height=600
    )
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return graphJSON, df_plot


@naso.route('/naso_tableview')
def naso_tableview():
    fsampleid = get_field("meta_sample_id2")
    fage = get_field("meta_age")
    print(fage)
    fdonor = get_field("meta_patient_id")
    fprediction = get_field("level2")
    fstatus = get_field("meta_severity")
    fdataset = get_field("meta_dataset")
    return render_template('tasks/naso_tableview.html',
                           fdonor=fdonor,
                           fage=fage,
                           fsampleid=fsampleid,
                           fprediction=fprediction,
                           fstatus=fstatus,
                           fdataset=fdataset)


#ids = [x["_id"] for x in list(db.single_cell_meta.find({}, {"_id": 1}))]

data = []


# Write big file
def write_file_byid(path, towrite):
    fn = path + '/ids.csv'
    print('writing ids to' + fn)
    file = open(fn, 'w+', newline='\n')
    #print(towrite[0])
    data = [[r['id']] for r in towrite]
    #print(data)
    with file:
        write = csv.writer(file)
        write.writerows(data)


# Write file
def write_file_meta(path, towrite):
    fn = path + '/meta.tsv'
    print('writing meta to' + fn)
    print(towrite[0])
    with open(fn, 'w') as file:
        file.write("\t".join([str(e) for e in towrite[0].keys()]))
        file.write('\n')

        for line in towrite:
            file.write("\t".join([str(e) for e in line.values()]))
            file.write('\n')


def write_umap(path, towrite):
    fn = path + '/umap.csv'
    print('writing umap to' + fn)
    file = open(fn, 'w+', newline='\n')
    #print(towrite[0])
    data = [[r['id'], r['UMAP1'], r['UMAP2']] for r in towrite]
    #print(data)
    with file:
        print("Writing file %s" % fn)
        write = csv.writer(file)
        write.writerows(data)
    return fn


# Write mtx is not okay, mem usage is too large and it will crash the server.
# def write_mtx(path, towrite):
#     fn = path + '/mtx.csv'
#     file = open(fn, 'w+', newline='\n')
#     print('writing mtx to' + fn)
#     #print(towrite[0])
#     data = [[r['gene_name'], r['barcode'], r['expression']] for r in towrite]
#     #print(data)
#     with file:
#         write = csv.writer(file)
#         write.writerows(data)
def write_10x_mtx(path,gene_dict,barcode_dict,counts, towrite):

    fn = path + '/matrix.mtx.gz'
    print('writing matrix.mtx.gz to' + fn)

    ##text=List of strings to be written to file
    with gzip.open(fn,'wb') as file:
        file.write("%%MatrixMarket matrix coordinate real general".encode())
        file.write('\n'.encode())
        file.write(" ".join([str(len(gene_dict)), str(len(barcode_dict)), str(counts)]).encode())
        file.write('\n'.encode())
        for line in towrite:
            file.write(" ".join([
                str(gene_dict[line['gene_name']]),
                str(barcode_dict[line['barcode']]),
                str(line['expression']),
            ]).encode())
            file.write('\n'.encode())


# Download big file
@naso.route('/download_meta', methods=['POST'])
def download_meta():
    meta = list(mongo.single_cell_meta.find({'_id': {'$in': collection_searched}}))
    print('writing ids to csv file only once, firstly load the data')
    write_file_byid(user_tmp[-1], meta)
    write_file_meta(user_tmp[-1], meta)
    #return send_file(user_tmp[-1] + '/ids.csv', as_attachment=True)
    return send_file(user_tmp[-1] + '/meta.tsv', as_attachment=True)


@naso.route('/download_umap', methods=['POST'])
def download_umap():
    f = user_tmp[-1] + "/ids.csv"
    if not os.path.isfile(f):
        id = mongo.single_cell_meta.find({'_id': {'$in': collection_searched}}, {'id': 1, '_id': 0})
        write_file_byid(user_tmp[-1], id)
        print(f)

    _byid = pd.read_csv(f).values.tolist()
    lookups = list(np.squeeze(_byid))
    umap = mongo.umap.find({'id': {'$in': lookups}})
    write_umap(user_tmp[-1], umap)
    return send_file(user_tmp[-1] + '/umap.csv', as_attachment=True)


@naso.route('/download_matrix', methods=['POST'])
def download_matrix():
    # Down load 10x matrix if not exist
    if(not (exists(user_tmp[-1] + '/matrix.mtx.gz'))):
        _byid = pd.read_csv(user_tmp[-1] + "/ids.csv").values.tolist()
        lookups = list(np.squeeze(_byid))
        start_time2 = time.time()
        mtx = mongo.matrix.find({'barcode': {'$in': lookups}})
        #query_counts = mtx.count()
        mtx = list(mtx)

        print("query finished --- %s seconds ---" % (time.time() - start_time2))

        ## Parse the barcode and gene based on name 
        def get_dict(path, sep="\t", header=None, save_path=None):
            # Transfrom the gene/barcode name to the corresponding number
            df_read = pd.read_csv(path, sep=sep, header=header)
            row_num = [i for i in range(1, len(df_read)+1)]
            row_name = list(df_read.iloc[:, 0].values)
            result_dict = dict(zip(row_name, row_num))
            if(not(save_path is None)):
                df_read.to_csv(save_path, sep="\t", header=False, index=False, compression='gzip')
            return result_dict

        # Save gene name
        if(not (exists(user_tmp[-1] + '/genes.tsv.gz'))):
            dict_gene = get_dict(TMP_FOLDER + "/genes.tsv", save_path=user_tmp[-1] + "/genes.tsv.gz")
        # Save barcodes
        if(not (exists(user_tmp[-1] + '/barcodes.tsv.gz'))):
            dict_barcode = get_dict(user_tmp[-1] + "/ids.csv", sep=",", save_path=user_tmp[-1] + "/barcodes.tsv.gz")
        write_10x_mtx(user_tmp[-1], dict_gene, dict_barcode, len(mtx), mtx)

    if(not (exists(user_tmp[-1] + '/matrix.zip'))):
        list_files = [
            user_tmp[-1] + '/matrix.mtx.gz',
            user_tmp[-1] + '/genes.tsv.gz',
            user_tmp[-1] + '/barcodes.tsv.gz',
            user_tmp[-1] + '/meta.tsv'
        ]
        with zipfile.ZipFile(user_tmp[-1] + '/matrix.zip', 'w') as zipMe:        
            for file in list_files:
                zipMe.write(file, compress_type=zipfile.ZIP_DEFLATED)

    return send_file(user_tmp[-1] + '/matrix.zip', as_attachment=True)


# set in-memory storage for collection of ids for meta data table display
collection = []
collection_searched = []

# http://www.dotnetawesome.com/2015/12/implement-custom-server-side-filtering-jquery-datatables.html
@naso.route('/api_db', methods=['GET', 'POST'])
@login_required
def api_db():
    data = []
    if request.method == 'POST':
        draw = request.form['draw']
        row = int(request.form['start'])
        rowperpage = int(request.form['length'])
        page_no = int(row/rowperpage + 1)
        search_value = request.form["search[value]"]
        print("draw: %s | row: %s | global search value: %s" % (draw, row, search_value))
        print(request.form)
        start = (page_no - 1)*rowperpage
        end = start + rowperpage
        map = {}
        for i in request.form:
            if ("[search][value]" in i) and (len(request.form[i]) != 0):
                column_value = request.form[i].split("|")
                if "0" in i:
                    search_column = "id"
                    map[search_column] = column_value
                elif "1" in i:
                    search_column = "meta_sample_id"
                    map[search_column] = column_value
                elif "2" in i:
                    search_column = "meta_age"
                    map[search_column] = column_value
                elif "3" in i:
                    search_column = "level2"
                    map[search_column] = column_value
                elif "4" in i:
                    search_column = "meta_patient_id"
                    map[search_column] = column_value
                elif "5" in i:
                    search_column = "meta_dataset"
                    map[search_column] = column_value
                else:
                    search_column = "meta_severity"
                    map[search_column] = column_value
        print(map)
        if search_value == '':
            if len(collection) == 0:
                ids = [x["_id"] for x in mongo.single_cell_meta.find({}, {"_id": 1})]
                collection.extend(ids)

flaskstarter/settings/__init__.py
# -*- coding: utf-8 -*-

from .views import settings

flaskstarter/settings/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user

from ..extensions import db
from ..user import Users
from .forms import ProfileForm, PasswordForm


settings = Blueprint('settings', __name__, url_prefix='/settings')


@settings.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    form = ProfileForm(obj=user,
                       email=current_user.email,
                       role_code=current_user.role_code,
                       status_code=current_user.status_code)

    if form.validate_on_submit():

        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        flash('Profile Changes Saved!', 'success')

    return render_template('settings/profile.html',
                           user=user, active="profile", form=form)


@settings.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(user)
        user.password = form.new_password.data

        db.session.add(user)
        db.session.commit()

        flash('Password updated.', 'success')

    return render_template('settings/password.html',
                           user=user, active="password", form=form)

flaskstarter/tasks/__init__.py
# -*- coding: utf-8 -*-

from .views import tasks
from .forms import MyTaskForm

flaskstarter/user/__init__.py
# -*- coding: utf-8 -*-

from .models import Users, UsersAdmin
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

flaskstarter/templates/tasks/add_task.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Add Task' %}

{% extends 'layouts/base.html' %}

{% block body %}
{% include 'layouts/banner.html' %}
  <div class="container contribute">
    <div class="row justify-content-center contribute-t"><h1>Contribute</h1></div>
    <div class="introduction">
      5.0 million single cell is build for the benefit of scientific community in health sector. Our team welcomes contributions of raw data of PBMC Single Cells, as long as it is consented for open access to the public.
    </div>
    <div class="row flex-column contribute-p">
      <div class="title">Data Submission Process</div>
      <div class="descp">We currenly accept csv form of dataset. Please follow the following steps to upload data.</div>
      <table class="intro-tb">
        <tr>
          <td><img src="{{url_for('static', filename='folder-2.png')}}" width="140" height="140"/></td>
          <td><img src="{{url_for('static', filename='Pointer.png')}}" width="95" height="95"/></td>
          <td><img src="{{url_for('static', filename='folder.png')}}" width="140" height="140"/></td>
          <td><img src="{{url_for('static', filename='Pointer.png')}}" width="95" height="95"/></td>
          <td><img src="{{url_for('static', filename='newspaper.png')}}" width="140" height="140"/></td>
        </tr>
        <tr>
          <th>
            Prepare metadata
          </th>
          <th></th>
          <th>
            Upload data
          </td>
          <th></th>
          <th>
            See and share
          </th>
        </tr>
        <tr>
          <td>in communication with our team</td>
          <td></td>
          <td>to a secure data storage area</td>
          <td></td>
          <td>accessioned data on the portal</td>
        </tr>
      </table>
    </div>
    <div class="button d-flex justify-content-center">
      <form action="{{ url_for('tasks.download')}}" method="post" style="display:inline-block">
        <button class="btn btn-outline-success" name="upload" type="submit"> Upload Data </button>
      </form>
    </div>
  </div>
{% include 'layouts/footer.html' %}
{% endblock %}

flaskstarter/templates/tasks/naso_tableview.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Explore' %}

{% extends 'layouts/base.html' %}

{% block body %}
{% include 'layouts/banner.html' %}
<script src="https://use.fontawesome.com/bbc48b41d3.js"></script>
<div style="margin:20px;padding:20px;">
   <div class="row justify-content-center">
        <h2>Explore Naso Data</h2>
   </div>
   <div class="jumbotron" style="background:#fff;">
        <h3>Filter</h3>
        <table style="width:85%">
            <tbody>
                <tr><td><div class="input-group mb-3"><input class="form-control" type="text" id="txt_id" placeholder="Search id"/></div></td></tr>
                <tr>
                    <td style="width:16%">
                    <select id="opt_sampleid" class="multibox" multiple="multiple">
                            <option label=" "></option>
                            {% for val in fsampleid %}
                            <option value="{{val}}">{{val}}</option>
                            {% endfor %}
                    </select>
                    </td>
                    <td style="width:16%">
                    <select id="opt_age" class="multibox" multiple="multiple">
                            <option label=" "></option>
                            {% for val in fage %}
                            <option value="{{val}}">{{val}}</option>
                            {% endfor %}
                    </select>
                    </td>
                    <td style="width:16%">
                    <select id="opt_prediction" class="multibox" multiple="multiple">
                            <option label=" "></option>
                            {% for val in fprediction %}
                            <option value="{{val}}">{{val}}</option>
                            {% endfor %}
                    </select>
                    </td>
                    <td style="width:16%">
                        <select id="opt_donor" class="multibox" multiple="multiple">
                            <option label=" "></option>
                            {% for val in fdonor %}
                            <option value="{{val}}">{{val}}</option>
                            {% endfor %}
                        </select>
                    </td>
                     <td style="width:16%">
                        <select id="opt_status" class="multibox" multiple="multiple">
                            <option label=" "></option>
                            {% for val in fstatus %}
                            <option value="{{val}}">{{val}}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td style="width:16%">
                        <select id="opt_dataset" class="multibox" multiple="multiple">
                            <option label=" "></option>
                            {% for val in fdataset %}
                            <option value="{{val}}">{{val}}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>
                    <input type="button" class="btn btn-primary" style="display:inline-block" value="Search" id="btnSearch" />
                    </td>
                    <td>
                    <input type="button" class="btn btn-primary" style="display:inline-block" value="Clear" id="btnClear" />
                     </td>
                     <td>
                    <button class="btn btn-primary" style="display:inline-block" class="hidden" id="btnAdvance">Advanced Search</button>
                    </td>
                </tr>

            </tbody>

        </table>
    </div>

    <div class="jumbotron" id="globalsearch" style="background:#fff">
    <h4>
       Global Search
    </h4>
    <input style="width:50%;display:inline-block" class="form-control" id="customSearchBox"/>
    <input type="button" style="display:inline-block" class="btn btn-primary" value="Search all" id="btnGSearch" />
    <input type="button" style="display:inline-block" class="btn btn-primary" value="Clear all" id="btnGClear" />
    </div>
    <table id="empTable" class="table table-hover table-striped table-responsive" style="width:100%">
        <thead>
            <tr>
                <th>id</th>
                <th>sampleId</th>
                <th>age</th>
                <th>prediction</th>
                <th>donor</th>
                <th>dataset</th>
                <th>status</th>
            </tr>
        </thead>
    </table>

    <div class="jumbotron">
       <h4>Please choose any of the option below for data manipulation.</h4>
    <form action="{{ url_for('naso.download_meta')}}" method="post" style="display:inline-block">
      <button class="btn btn-primary" name="download" type="submit"> Download metadata </button>
    </form>

    <form action="{{ url_for('naso.download_umap')}}" method="post" style="display:inline-block">
      <button class="btn btn-primary" name="download_umap" type="submit"> Download UMAP </button>
    </form>

    <form action="{{ url_for('naso.show_plot')}}" method="get" style="display:inline-block">
      <button class="btn btn-primary" name="show_plot" type="submit"> Show UMAP plot </button>
    </form>

    <form action="{{ url_for('naso.download_matrix')}}" method="post" style="display:inline-block">
      <button class="btn btn-primary" name="download_matrix" type="submit"> Download matrix </button>
    </form>
    </div>

  </div>
{% endblock %}

{% block scripts %}

<style>
    .dataTables_filter { display: none;}
    .page-item.active .page-link {
    background-color: #04AA6D !important;
    border: 1px solid #ffffff;
    }
    .page-link {
    color: black !important;
    }


</style>
<script>

$(document).ready(function() {
    $("#globalsearch").hide();

    $("#btnAdvance").click(function() {
        $("#globalsearch").toggle();
    });

    $('#opt_sampleid').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search for something...',
            nonSelectedText: 'Sample id',
            buttonWidth: '150px',
            maxHeight: 450
    });

    $('#opt_age').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search for something...',
            nonSelectedText: 'Age',
            buttonWidth: '150px',
            maxHeight: 450
    });

    $('#opt_donor').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search for something...',
            nonSelectedText: 'Donor',
            buttonWidth: '150px',
            maxHeight: 450
    });

    $('#opt_dataset').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search for something...',
            nonSelectedText: 'Dataset',
            buttonWidth: '150px',
            maxHeight: 450
    });

    $('#opt_status').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search for something...',
            nonSelectedText: 'Status',
            buttonWidth: '150px',
            maxHeight: 450
    });

    $('#opt_prediction').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search for something...',
            nonSelectedText: 'Cell Type',
            buttonWidth: '150px',
            maxHeight: 450
    });

    $('#empTable').DataTable({
                'processing':true,
                'language': {
                    'processing': '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>'
                 },
                'serverSide': true,
                'serverMethod': 'post',
                'ajax': {
                    'url':'{{ url_for('naso.api_db')}}'
                },
                'lengthMenu': [[10, 25, 50, 100], [10, 25, 50, 100]],
                searching: true,
                sort: false,
                'columns': [
                    { data: 'id' },
                    { data: 'sample_id' },
                    { data: 'age' },
                    { data: 'prediction' },
                    { data: 'donor' },
                    { data: 'dataset' },
                    { data: 'status'}
                ],
                "columnDefs": [
                { "width": "28%", "targets": 0 },
                { "width": "14%", "targets": 1 },
                { "width": "7%", "targets": 2 },
                { "width": "7%", "targets": 3 },
                { "width": "14%", "targets": 4 },
                { "width": "14%", "targets": 5 },
                { "width": "14%", "targets": 6 }
                ],
                initComplete : function() {
                    var input = $('#customSearchBox').unbind(),
                        self = this.api(),
                        $searchButton = $('#btnGSearch')
                                   .text('search')
                                   .click(function() {
                                      self.search(input.val()).draw();
                                   }),
                        $clearButton = $('#btnGClear')
                                   .text('clear')
                                   .click(function() {
                                      input.val('');
                                      $searchButton.click();
                                   })
                }

            });

            oTable = $('#empTable').DataTable();
            $('#btnSearch').click(function () {
                //Apply search for Employee Name // DataTable column index 0
                oTable.columns(0).search($('#txt_id').val().trim());
                //Apply search for Country // DataTable column index 3
                oTable.columns(1).search($('#opt_sampleid').val().join("|"));
                oTable.columns(2).search($('#opt_age').val().join("|"));
                oTable.columns(3).search($('#opt_prediction').val().join("|"));
                oTable.columns(4).search($('#opt_donor').val().join("|"));
                oTable.columns(5).search($('#opt_dataset').val().join("|"));
                oTable.columns(6).search($('#opt_status').val().join("|"));
                //hit search on server
                oTable.draw();
            });
            $('#btnClear').click(function () {

                oTable.columns().search('').draw();
                document.getElementById("txt_id").value = "";
                $("#opt_sampleid").multiselect('clearSelection');
                $('#opt_age').multiselect('clearSelection');
                $('#opt_prediction').multiselect('clearSelection');
                $('#opt_donor').multiselect('clearSelection');
                $('#opt_dataset').multiselect('clearSelection');
                $('#opt_status').multiselect('clearSelection');


            });

});


$('select').selectpicker();

  document.getElementById('select').onclick = function () {
    var selected = [];
    for (var option of document.getElementById('multiselect').options) {
      if (option.selected) {
        selected.push(option.value);
      }
    }
    alert("Successfully selected the following donors for filtering" + selected);

  }
</script>
{% endblock %}