flaskstarter/frontend/forms.py
# -*- coding: utf-8 -*-

from flask import Markup

from flask_wtf import FlaskForm
from wtforms import (ValidationError, HiddenField, BooleanField, TextField,
                     PasswordField, SubmitField, TextAreaField)
from wtforms.validators import Required, Length, EqualTo, Email
from wtforms.fields.html5 import EmailField

from ..utils import (NAME_LEN_MIN, NAME_LEN_MAX, PASSWORD_LEN_MIN,
                     PASSWORD_LEN_MAX)

from ..user import Users

terms_html = Markup('<a target="blank" href="/terms">Terms of service</a>')


class LoginForm(FlaskForm):
    next = HiddenField()
    login = TextField(u'Email', [Required()])
    password = PasswordField('Password', [Required(),
                                          Length(PASSWORD_LEN_MIN,
                                                 PASSWORD_LEN_MAX)])
    remember = BooleanField(' Remember me')
    submit = SubmitField('      Sign in')


class SignupForm(FlaskForm):
    next = HiddenField()
    name = TextField(u'Name', [Required(), Length(NAME_LEN_MIN, NAME_LEN_MAX)])
    email = EmailField(u'Email', [Required(), Email()])
    password = PasswordField(u'Password',
                             [Required(), Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)],
                             description=u' 6 or more characters.')
    agree = BooleanField(u' Agree to the ' + terms_html, [Required()])
    submit = SubmitField('      Sign up')

    def validate_email(self, field):
        if Users.query.filter_by(email=field.data).first() is not None:
            raise ValidationError(u'This email is taken')


class RecoverPasswordForm(FlaskForm):
    email = EmailField(u'Your email', [Email()])
    submit = SubmitField('       Send')


class ChangePasswordForm(FlaskForm):
    email_activation_key = HiddenField()
    email = HiddenField()
    password = PasswordField(u'Password', [Required()])
    password_again = PasswordField(u'Password again', [EqualTo('password', message="Passwords don't match")])
    submit = SubmitField('Save')


class ContactUsForm(FlaskForm):
    name = TextField(u'Name', [Required(), Length(max=64)])
    email = EmailField(u'Your Email', [Required(), Email(), Length(max=64)])
    subject = TextField(u'Subject', [Required(), Length(5, 128)])
    message = TextAreaField(u'Your Message', [Required(), Length(10, 1024)])
    submit = SubmitField('Submit')

flaskstarter/tasks/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, SelectField
from wtforms.validators import Required, Length

class MyTaskForm(FlaskForm):
    task = TextAreaField(u'Your Task', [Required(), Length(5, 2048)])
    submit = SubmitField(u'Save Task')

class UmapForm(FlaskForm):
    def __init__(self,choices=[('def','Default')]):
        self.cell_color = SelectField('cell_color',choices=choices)

flaskstarter/__init__.py
# -*- coding: utf-8 -*-

from .app import create_app

flaskstarter/app.py
# -*- coding: utf-8 -*-

from flask import Flask

from .config import DefaultConfig
from .user import Users, UsersAdmin
from .settings import settings
from .tasks import tasks
from .naso_tableview import naso
from .frontend import frontend, ContactUsAdmin
from .extensions import db, mail, cache, login_manager, admin, mongo
from .utils import pretty_date
import logging
import os
from datetime import timedelta

from pymongo import MongoClient
from .model.umap import UmapView
from .model.meta import MetaView

# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
    settings,
    tasks,
    naso
)

logging.basicConfig(level=logging.DEBUG,
                   format='[%(asctime)s]: {} %(levelname)s %(message)s'.format(os.getpid()),
                   datefmt='%Y-%m-%d %H:%M:%S',
                   handlers=[logging.StreamHandler()])

logger = logging.getLogger()


def create_app(config=None, app_name=None, blueprints=None):
    # Create a Flask app

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name,
                instance_relative_config=True)

    # Add 0627 by junyi
    # app.config['LOGIN_DISABLED'] = True
    app.config['SECRET_KEY'] = os.urandom(24)
    app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=30)

    # add db


    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app


def configure_app(app, config=None):
    # Different ways of configurations i.e local or production
    logger.info(f"Starting app in %s environment" % os.getenv('FLASK_ENV'))
    flask_env = os.environ.get('FLASK_ENV')
    if 'development' in flask_env:
        print('configuring for development')
        app.config.from_object(DefaultConfig)
    # if exists under root ./instance/X.cfg
    # app.config.from_pyfile('secret_config.cfg')
    # print(app.instance_path)
    if config:
        app.config.from_object(config)


def configure_extensions(app):

    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # flask-cache
    cache.init_app(app)

    # flask-admin
    # sqlite db data
    admin.add_view(ContactUsAdmin(db.session))
    admin.add_view(UsersAdmin(db.session))

    # mongo db data
    admin.add_view(UmapView(mongo['umap']))
    admin.add_view(MetaView(mongo['single_cell_meta_country']))

    admin.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return Users.query.get(id)
    login_manager.setup_app(app)


def configure_blueprints(app, blueprints):
    # Configure blueprints in views

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    # Configure logging

    if app.debug:
        # Skip debug and test mode. Better check terminal output.
        return

    # TODO: production loggers for (info, email, etc)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return "Oops! You don't have permission to access this page.", 403

    @app.errorhandler(404)
    def page_not_found(error):
        return "Opps! Page not found.", 404

    @app.errorhandler(500)
    def server_error_page(error):
        return "Oops! Internal server error. Please try after sometime.", 500

flaskstarter/frontend/__init__.py
# -*- coding: utf-8 -*-

from .models import ContactUs, ContactUsAdmin

from .views import frontend

flaskstarter/frontend/views.py
# -*- coding: utf-8 -*-

from uuid import uuid4

from itsdangerous import URLSafeSerializer

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect)
from flask_login import (login_required, login_user, current_user,
                         logout_user, login_fresh)


from ..tasks import MyTaskForm
from ..user import Users, ACTIVE
from ..extensions import db, login_manager, mongo
from .forms import (SignupForm, LoginForm, RecoverPasswordForm,
                    ChangePasswordForm, ContactUsForm)
from .models import ContactUs
from ..utils import TMP_FOLDER
from ..emails import send_async_email
import sqlite3
from datetime import datetime
import os
import pandas as pd
from bson.son import SON
import pprint

frontend = Blueprint('frontend', __name__)

@frontend.route('/dashboard')
@login_required
def dashboard():

    _task_form = MyTaskForm()

    return render_template('dashboard/dashboard.html', task_form=_task_form, _active_dash=True)


def get_all_study_meta():
    res = list(mongo.pbmc_all_study_meta_v4.find())
    print(res[1])
    #uniq_field = mongo.single_cell_meta.aggregate([{"$group": {"_id": '$%s' % field_name}}]);
    #key = [r['_id'] for r in uniq_field]
    
    return res


def get_field_count():
    pipeline = [
        {"$unwind": "$level2"},
        {"$group": {"_id": "$level2", "count": {"$sum": 1}}},
        {"$project": SON([("count", 1), ("_id", 1)])}
    ]

    res = list(mongo.single_cell_meta.aggregate(pipeline))

    # for item in res:
    #     print(item)
    #     print(item['_id'])
    #     print(item["count"])
    return res
    
# Replace old get field count method    
def get_celltype_count():
    # db.createCollection('stats_celltype_count')
    # db.stats_celltype_count.insertMany(db.single_cell_meta_v4.aggregate([{"$group": {"_id": "$level2", "count":{"$sum": 1}}}]).toArray())
    collection_name = 'stats_celltype_count'
    res = list(mongo.stats_celltype_count.find())

    return res

def get_overview():
    res = list(mongo.stats_meta_overview.find())

    return res

# Load landing page data
filepath = os.path.abspath(os.getcwd())
filename = os.path.join(
    filepath, 'flaskstarter/PBMC_study_meta/PBMC_study_meta.csv')
df = pd.read_csv(filename)
df = df.dropna(subset=['Country Code'])

@frontend.route('/', methods=["GET", "POST"])
def index():
    data = df.to_dict()
    fdataset = get_all_study_meta()
    res = get_celltype_count()
    counting = get_overview()
    counts = counting
    #pprint.pprint(res)
    if current_user.is_authenticated:
        return render_template('tasks/landing.html',  data=data, _active_home=True, fdataset=fdataset, fcelltype=res, counting=counting, counts=counts)
    return render_template('tasks/landing.html',  data=data, _active_home=True, fdataset=fdataset, fcelltype=res, counting=counting, counts=counts)
# @frontend.route('/')
# def index():
#     # current_app.logger.debug('debug')
#     if current_user.is_authenticated:
#         return redirect(url_for('tasks.table_view'))

#     return render_template('tasks/landing.html', _active_home=True)

@frontend.route('/tutorial', methods=['GET', 'POST'])
def tutorial():
    return render_template('frontend/tutorial.html')

@frontend.route('/contact-us', methods=['GET', 'POST'])
def contact_us():
    form = ContactUsForm()

    if form.validate_on_submit():
        _contact = ContactUs()
        form.populate_obj(_contact)
        db.session.add(_contact)
        db.session.commit()

        flash('Thanks! We\'ll get back to you shortly!', 'success')

        return redirect(url_for('frontend.contact_us'))

    return render_template('frontend/contact_us.html', form=form)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))
    print("Debug login")   
    print(request)                 

    if form.validate_on_submit():
        user, authenticated = Users.authenticate(form.login.data, form.password.data)
        print(request.form)
        print(request.args)            

        if user and authenticated:

            if user.status_code != 2:
                flash("Please verify your email address to continue", "danger")
                return redirect(url_for('frontend.login'))

            remember = request.form.get('remember') == 'y'

            if login_user(user, remember=remember):
                flash("Logged in", 'success')
            return redirect(form.next.data or url_for('frontend.index'))
        else:
            flash('Sorry, invalid login', 'danger')

    return render_template('frontend/login.html', form=form, _active_login=True)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out', 'success')
    return redirect(url_for('frontend.index'))


@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.dashboard'))

    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = Users()
        user.status_code = 2
        user.account_type = 0
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        confirm_user_mail(form.name.data, form.email.data)

        flash(u'Registration successful! Please verify!', 'success')
        return redirect(url_for('frontend.login'))

    return render_template('frontend/signup.html', form=form,
                           _active_signup=True)


def confirm_user_mail(name, email):
    s = URLSafeSerializer('serliaizer_code')
    key = s.dumps([name, email])

    subject = 'Confirm your account for ' + current_app.config['PROJECT_NAME']
    url = url_for('frontend.confirm_account', secretstring=key, _external=True)
    html = render_template('macros/_confirm_account.html',
                           project=current_app.config['PROJECT_NAME'],
                           url=url)

    send_async_email(subject, html, email)


@frontend.route('/confirm_account/<secretstring>', methods=['GET', 'POST'])
def confirm_account(secretstring):
    s = URLSafeSerializer('serliaizer_code')
    uname, uemail = s.loads(secretstring)
    user = Users.query.filter_by(name=uname).first()
    user.status_code = ACTIVE
    db.session.add(user)
    db.session.commit()
    flash(u'Your account was confirmed succsessfully!!!', 'success')
    return redirect(url_for('frontend.login'))


@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():

    if current_user.is_authenticated:
        if not login_fresh():
            return login_manager.needs_refresh()

    form = ChangePasswordForm(email_activation_key=request.values["email_activation_key"],
                              email=request.values["email"])

    if form.validate_on_submit():
        update_password(form.email.data, form.email_activation_key.data, form.password.data)
        flash(u"Your password has been changed, log in again", "success")
        return redirect(url_for("frontend.login"))

    return render_template("frontend/change_password.html", form=form)


def update_password(email, email_activation_key, password):
    user = Users.query.filter_by(email_activation_key=email_activation_key, email=email).first()
    user.password = password
    user.email_activation_key = None
    db.session.add(user)
    db.session.commit()


@frontend.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()

        if user:
            flash('Please see your email for instructions on how to access your account', 'success')

            user.email_activation_key = str(uuid4())
            db.session.add(user)
            db.session.commit()

            subject = 'Reset your password in ' + current_app.config['PROJECT_NAME']
            url = url_for('frontend.change_password', email=user.email,
                          email_activation_key=user.email_activation_key, _external=True)
            html = render_template('macros/_reset_password.html', project=current_app.config['PROJECT_NAME'],
                                   name=user.name, url=url)

            send_async_email(subject, html, user.email)

            return render_template('frontend/reset_password.html', form=form)
        else:
            flash('Sorry, no user found for that email address', 'danger')

    return render_template('frontend/reset_password.html', form=form)


@frontend.route('/terms')
def terms():
    return "To be updated soon.."


@frontend.route('/about-us')
def about_us():
    return "To be updated soon.."

flaskstarter/naso_tableview/__init__.py
# -*- coding: utf-8 -*-

from .views import naso

flaskstarter/settings/__init__.py
# -*- coding: utf-8 -*-

from .views import settings

flaskstarter/settings/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user

from ..extensions import db
from ..user import Users
from .forms import ProfileForm, PasswordForm


settings = Blueprint('settings', __name__, url_prefix='/settings')


@settings.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    form = ProfileForm(obj=user,
                       email=current_user.email,
                       role_code=current_user.role_code,
                       status_code=current_user.status_code)

    if form.validate_on_submit():

        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        flash('Profile Changes Saved!', 'success')

    return render_template('settings/profile.html',
                           user=user, active="profile", form=form)


@settings.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(user)
        user.password = form.new_password.data

        db.session.add(user)
        db.session.commit()

        flash('Password updated.', 'success')

    return render_template('settings/password.html',
                           user=user, active="password", form=form)

flaskstarter/tasks/__init__.py
# -*- coding: utf-8 -*-

from .views import tasks
from .forms import MyTaskForm

flaskstarter/user/__init__.py
# -*- coding: utf-8 -*-

from .models import Users, UsersAdmin
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

flaskstarter/templates/frontend/change_password.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Change Password' %}

{% extends 'layouts/base.html' %}

{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-4 offset-4">
        {{ render_form(url_for('frontend.change_password'), form)}}
      </div>
    </div>
  </div>
{% endblock %}

flaskstarter/templates/frontend/contact_us.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Contact us' %}

{% extends 'layouts/base.html' %}

{% block body %}
<div class="d-flex flex-column justify-content-center" id="banner">
  <div class="d-flex justify-content-center boldH72">
    <h1>Contact us</h1>
  </div>
  <div class="d-flex justify-content-center regularH20">
    <h5 class="text-center">For enquiries, comments or collaboration opportunities, <br>
      please feel free to contact us through the following ways.</h5>
  </div>
</div>
<div id="contact" class="justify-content-center">
  <div class="contactboard">
    <div class="row" style="padding-bottom:40px">
      <div class="col-lg">
        <div class="row" style="padding-bottom: 30px;">
          <div class="col-4 mediumH22">
            Tel
          </div>
          <div class="col-8 regularH160 justify-content-start">
            +852 3910 3800
          </div>
        </div>
        <div class="row" style="padding-bottom: 30px;">
          <div class="col-4 mediumH22">
            Fax
          </div>
          <div class="col-8 regularH160 justify-content-start">
            +852 2793 3233
          </div>
        </div>
        <div class="row" style="padding-bottom: 30px;">
          <div class="col-4 mediumH22">
            Email
          </div>
          <div class="col-8 regularH160 justify-content-start">
            covidscope@gmail.com
          </div>
        </div>
        <div class="row" style="padding-bottom: 30px;">
          <div class="col-4 mediumH22">
            Website
          </div>
          <div class="col-8 regularH160 justify-content-start">
            <a href="https://www.d24h.hk/" style="color: #000000" target="_blank">https://www.d24h.hk/</a>
          </div>
        </div>
      </div>
      <div class="col-lg">
        <div class="mediumH22">
          Address
          <hr style="border: 1px solid #045547;">
        </div>
        <div class="regularH160">Units 1201-1206, 1223 & 1225, 12/F, Building 19W, 19 Science Park West Avenue, Hong
          Kong Science Park,
          Pak Shek Kok, New Territories, Hong Kong.</div>

      </div>
    </div>
    <div class="row justify-content-center"><iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3688.041067853891!2d114.20601421494844!3d22.427480043933667!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404090e338ac047%3A0x38c13308a5ff95c4!2sLaboratory%20of%20Data%20Discovery%20for%20Health%20Limited!5e0!3m2!1szh-TW!2shk!4v1647903842096!5m2!1szh-TW!2shk"
        width="750" height="560" style="border:0;" allowfullscreen="" loading="lazy"></iframe></div>
  </div>



</div>
</div>

<!--<div class="container data">
  <div class="row mt-5">
    <div class="col-4 offset-4">
      {{ render_form(url_for('frontend.contact_us'), form)}}
    </div>
  </div>
</div>-->
{% endblock %}

flaskstarter/templates/frontend/landing.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Home' %}

{% extends 'layouts/base.html' %}

{% block body %}
{% include 'layouts/banner.html' %}
<div class="container">
  <div class="row justify-content-center">
    <h2>Home</h2>
  </div>

</div>
{% endblock %}

{% block scripts %}




{% endblock %}

flaskstarter/templates/frontend/login.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Login' %}

{% extends 'layouts/base.html' %}

{% block body %}
<div class="log-in">
  <div class="log-container flex-column">
    <div class="container" style="margin: 0px; padding:0px;">
      <div class="row justify-content-center">
        <h3>Sign in</h3>
      </div>
      {{ render_form(url_for('frontend.login'), form)}}
      <div class="row justify-content-center">
        <p class="mb-2 text-sm mx-auto"> Don't have an account? <a href="{{url_for('frontend.signup')}}"
            class="text-info text-gradient font-weight-bold">Sign up</a> </p>
      </div>
      <div class="row justify-content-center">
        <a href="{{url_for('frontend.reset_password')}}" class="auth-link">Forgot password?</a>
      </div>
    </div>



  </div>
</div>
{% endblock %}

flaskstarter/templates/frontend/reset_password.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Reset Password' %}

{% extends 'layouts/base.html' %}

{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-4 offset-4">
        {{ render_form(url_for('frontend.reset_password'), form)}}
      </div>
    </div>
  </div>
{% endblock %}

flaskstarter/templates/frontend/signup.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Sign up' %}

{% extends 'layouts/base.html' %}

{% block body %}
<div class="sign-up">
  <div class="log-container flex-column">
    <h3>Sign up</h3>
    {{ render_form(url_for('frontend.signup'), form)}}
  </div>
</div>
{% endblock %}

flaskstarter/templates/frontend/tutorial.html
{% set page_title = 'Tutorial' %}

{% extends 'layouts/base.html' %}

{% block body %}
<div class="section03" style="min-height: 100vh;">
  <div class="container" style="padding: 0px;">
    <div class="row justify-content-center">
      <div class="boldauto36" style="margin-bottom: 50px;">Tutorial</div>
    </div>
    <div class="row">
      <div class="container tutorialCard collapsible" style="padding: 0px; margin-bottom: 24px;">
        <div class="row tutorialTitle boldH160">Guide to use Covidscope Webserver（Video)</div>
        <div class="row justify-content-center">
        <iframe width="1680" height="945" src="https://www.youtube.com/embed/cGNOjUovm5c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="row container collapsible-text"
          style="padding: 30px 40px 30px 40px; border-top: 1px solid #B4B6B8;">
          <div class="row tutorialContent regularauto16">
            Also find the down-stream analysis tutorial in following link after you downloaded data from Covidscope ....
          </div>
          <div class="row tutorialLink">
            <a
              href="https://sydneybiox.github.io/scdneyAdvancedPhenotyping/articles/advanced_phenotyping.html">https://sydneybiox.github.io/scdneyAdvancedPhenotyping/articles/advanced_phenotyping.html</a>
          </div>
        </div>
      </div>
      <div class="container tutorialCard collapsible" style="padding: 0px; margin-bottom: 24px;" hidden>
        <div class="row tutorialTitle boldH160">How to...</div>
        <div class="row container collapsible-text"
          style="padding: 30px 40px 30px 40px; border-top: 1px solid #B4B6B8;">
          <div class="row tutorialContent regularauto16">
            If you want to ....
          </div>
          <div class="row tutorialLink">
            <a href="http://www.d24h.tutorial.hk">http://www.d24h.tutorial.hk</a>
          </div>
        </div>
      </div>
      <div class="container tutorialCard collapsible" style="padding: 0px; margin-bottom: 24px;" hidden>
        <div class="row tutorialTitle boldH160">How to...</div>
        <div class="row container collapsible-text"
          style="padding: 30px 40px 30px 40px; border-top: 1px solid #B4B6B8;">
          <div class="row tutorialContent regularauto16">
            If you want to ....
          </div>
          <div class="row tutorialLink">
            <a href="http://www.d24h.tutorial.hk">http://www.d24h.tutorial.hk</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
</div>

{% endblock %}